Document: bloonix-plugins-sensors
Title: Debian bloonix-plugins-sensors Manual
Author: <insert document author here>
Abstract: This manual describes what bloonix-plugins-sensors is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/bloonix-plugins-sensors/bloonix-plugins-sensors.sgml.gz

Format: postscript
Files: /usr/share/doc/bloonix-plugins-sensors/bloonix-plugins-sensors.ps.gz

Format: text
Files: /usr/share/doc/bloonix-plugins-sensors/bloonix-plugins-sensors.text.gz

Format: HTML
Index: /usr/share/doc/bloonix-plugins-sensors/html/index.html
Files: /usr/share/doc/bloonix-plugins-sensors/html/*.html
